### ISSUE TITLE
Breaking change in 4.0.1 due to globby 8.0.0

### ISSUE THREAD

**Issue by UncleWalt** [SBoudrias/mem-fs-editor#111]
Hi,

I just noticed all of my yeoman generators stopped working after updating yeoman-generator and its dependencies. Version 4.0.1 of this package is now using globby ^8.0.0 (#99). This version of globby replaced **node-glob** with **fast-glob**. **fast-glob** has slightly different options (breaking change in my case: the `ignore` option doesn't accept a string, only an array of strings) and some other quirks (sindresorhus/globby#80, sindresorhus/globby#79, ...).

**Comment by SBoudrias** [comment]
Sorry about that, it's a bit hard sometime to follow through package updates and knows if it'll break someone else specific usage.

I'll not plan to revert the change just now; but I'll reconsider if a lot of people seems to have been impacted by this change.

**Comment by michael5r** [comment]
We have the same issue - all of our Yeoman generators broke because of this change.

**Comment by Awk34** [comment]
This broke me as well. Reverting to 4.0.0 fixes it. Here's the error:
```
Trying to copy from a source that does not exist: C:\somepath\generator-angular-fullstack\templates\app\client\app\account(auth)\account.module.js
```

It seems it doesn't like parens in paths.

**Comment by sonicdoe** [comment]
I’m also running into this issue with my Yeoman generator [@sonicdoe/generator-node](https://github.com/sonicdoe/generator-node). I’ve also opened an issue over at https://github.com/yeoman/generator/issues/1076.

**Comment by SBoudrias** [comment]
Latest patch reverts to previous version of globby. And a new major (v5) is using `globby@8`
