### ISSUE TITLE
Support for templates in destination paths is using characters reserved on Windows.

### ISSUE THREAD

**Issue by jakub300** [SBoudrias/mem-fs-editor#115]
Recently added support for templates in destination paths (2bb43b7, #106) is using `<` and `>` that are [reserved characters on Windows](https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx). Because of that is it currently impossible to checkout master and any project/generator that would use this would break.

**Comment by jakub300** [comment]
In case of repository there is `nested-<%= tag %>-package` directory in tests. It is making impossible to checkout repository. I will show exact error when I get back home.

In real use (like yeoman generator) my understanding is that templates would be part of folder and file names inside of the generator so they have to be written to file system when generator is installed and later they would be replaced when generating project.

**Comment by SBoudrias** [comment]
Oh my bad, I totally missed that... We shouldn't have a folder with `<` in the path name.

The template should only be applied when creating a dynamic destination. It shouldn't be in the actual path source.

**Comment by LarsOL** [comment]
Now that directory variables have been removed. How do we implement this? I am using yeoman which uses this library, and want to template the package (directory) names.

Are there any examples?

**Comment by asmagin** [comment]
I've created PR #117, that introduce `processPath` function. It works similar to `process` but applied to a file path.

**Comment by st7art22** [comment]
Hello from 2023!
The answer to this problem is in the 4th parameter
Change file and folder names from `<%= name %>` to `{#= name #}`
For example like this
```javascript

this.fs.copyTpl(
  this.templatePath(),
  this.destinationPath(),
  {
    name: this.props.name,
  },
  {
    name: this.props.name,
    delimiter: "#",
    openDelimiter: "{",
    closeDelimiter: "}"
  }
);
```
