### ISSUE TITLE
[Feature request] move / rename function

### ISSUE THREAD

**Issue by callumacrae** [SBoudrias/mem-fs-editor#13]
A move function would be helpful, and as far as I can see, also pretty easy to write.

I'm not so sure about a rename function—possibly a function which behaves pretty much the same as the move function, but doesn't change the directory?

```
fs.move('dir/file.js', 'dir/different-name.js'); // dir/different-name.js

fs.rename('dir/file.js', 'different-name.js'); // dir/different-name.js
```

Could be confusing though. Might be best just to stick to one function.

**Comment by blai** [comment]
implemented by #17
