### ISSUE TITLE
mem-fs-editor in reactjs

### ISSUE THREAD

**Issue by mohitsaini2114** [SBoudrias/mem-fs-editor#137]
I wan to use copyTpl but in Reactjs. I have one json object created from user inputs. I want to generate a destination file based on json object  using my template file.

Any leads would be appreciated. Thanks

**Comment by SBoudrias** [comment]
You'll need to create a `mem-fs` store that works in the browser. `mem-fs-editor` should work without issue.

Feel free to send a PR if you find issues and want to fix them. For myself, browsers environment is out the scope I'm willing to maintain/support as part of this project.
