### ISSUE TITLE
#copy() should provide options 'override' to resolve conflicts between 'from' and 'to'

### ISSUE THREAD

**Issue by blai** [SBoudrias/mem-fs-editor#14]
Currently, copying a file to a path that is associated with another existing file would override the existing file, without warning or options to override such behavior.

`#copy(from, to, options)` should provide an option `options.override` that allows more flexibility:

* When `options.override` is set to `true`, the function should have exactly the same behavior as today.
* When `options.override` is set to `false`, the function should throw exception if conflicting content is found between `from` and `to`
* When `options.override` is a function, the function should be something like `function (oldConent, newContent) { return desieredContent; }`

**Comment by SBoudrias** [comment]
I feel like this use case could be handled by a custom commit filter: https://github.com/SBoudrias/mem-fs-editor#commitfilters-callback

How would you feel about that?

**Comment by blai** [comment]
I actually thought about that, but commit filter only tracks the latest state of the vinyl object, `copy`, on the other hand, may have been triggered multiple times prior to the calling of `commit`. In other words, I could have missed the window to make the decision of whether to override contents or not when calling `copy`.

**Comment by SBoudrias** [comment]
I'm actually going to close this one as mem-fs-editor doesn't know anything about conflicts. Only yeoman-generator does.
