### ISSUE TITLE
the process function of fs.copy's options can support Promise

### ISSUE THREAD

**Issue by ycjcl868** [SBoudrias/mem-fs-editor#143]
https://github.com/SBoudrias/mem-fs-editor/blob/40c1ce840bdf2b7d333d69954593f3d0fd9f09d9/lib/actions/copy.js#L65

my code:

```js
this.fs.copy(path, targetPath, {
   async process(content) {
       const newContent = await ..
       return newContent;
   }
})
```

**Comment by SBoudrias** [comment]
This won't work; and it kind of cannot work.

mem-fs is built to be a synchronous fs store. There's no built-in piece to make it support asynchronous operations and for this to work with where it is integrated.

I don't intend to change this as after this mem-fs would be a completely new project.

You can probably update your own code to work under this limitation.
