### ISSUE TITLE
extendJson doesn't play nicely with arrays

### ISSUE THREAD

**Issue by tomukasas** [SBoudrias/mem-fs-editor#146]
When I want extend json file with array, the array is getting replaced instead of extended. For example I have a an array like this in `.babelrc`:

`"plugins": [
        "transform-remove-console"
      ]`

And I want to extend that array with:

`"plugins": [
        "transform-react-remove-prop-types",
        "@babel/plugin-transform-react-constant-elements"
      ]` 

The final outcome will replace the original array in `.babelrc` file with extended array, instead of merging them:

`"plugins": [
        "transform-react-remove-prop-types",
        "@babel/plugin-transform-react-constant-elements"
      ]`

I imagine the problem is with the `deep-extend` npm package. It is clearly visible in their example that arrays are replaced, instead of being extended (look at property `j:` in their example).

**Comment by SBoudrias** [comment]
The problem with array is that they're ordered. So we cannot simply do a "merge" operation as it could have side-effects.

I think the current behavior within the library is good and predictable for most use cases (you can check other "merge" function implementations in other libraries, arrays are always overwritten)

For your use case, it is a bit more verbose, but you'd want to implement the merge manually. e.g

```js
const obj = readJSON('path');
obj.plugins = obj.plugins.concat(['new-plugin']);
writeJSON('path', obj);
```
