### ISSUE TITLE
When using copyTpl how can I not copy over certain files?

### ISSUE THREAD

**Issue by MarleyDabb** [SBoudrias/mem-fs-editor#180]
```
this.fs.copyTpl(
                    this.templatePath(`plugins/${this.answers[plugin]}/**/*`),
                    this.destinationPath(`public/${this.answers.name}`),
                    {answers: this.answers},
                    {globOptions: {options: ['test', 'test.js']}}
                )
```

I want to be able to copy a template but exclude a handful of files, as you can see hear I'm trying to stop test.js from being copied over but the above code is not working. Any ideas?

**Comment by SBoudrias** [comment]
Hi, I think you need to use the `ignore` part of `globOptions`; like described here: https://github.com/mrmlnc/fast-glob#ignore

I'll close this issue since it just seems like a mistake from the code example you left. Cheers!
