### ISSUE TITLE
Copy moves a glob like file to a subfolder

### ISSUE THREAD

**Issue by timlrx** [SBoudrias/mem-fs-editor#193]
This seems to apply to glob like file names like `[slug].js` or `*slug.js`, with or without `noGlob`.

Example:
```js
import { create as createStore } from 'mem-fs'
import { create as createEditor } from 'mem-fs-editor'

const fileName = '[slug].js'
const store = createStore()
const fs = createEditor(store)
fs.copy(
  '/home/user/[slug].js',
  '/home/user/temp/[slug].js',
  { noGlob: true }
)
fs.commit()
```

The file is copied to '/home/user/temp/[slug].js/[slug].js' instead of '/home/user/temp/[slug].js'. 
System info: Ubuntu 18 with node v16.10.0.

**Comment by timlrx** [comment]
The problem is coming from this [line](https://github.com/SBoudrias/mem-fs-editor/blob/master/lib/actions/copy.js#L41).

How about changing it to the following:
```
if (
    Array.isArray(from) ||
    !this.exists(from) ||
    (globby.hasMagic(normalize(from)) && !options.noGlob)
  ) 
```
so that it respects the `noGlob` option and not force it to a subdirectory

**Comment by mshima** [comment]
@timlrx can you provide the PR?

**Comment by SBoudrias** [comment]
`mem-fs-editor@9.4.0` is out 🙌
