### ISSUE TITLE
_.slugify() no longer supported in templating

### ISSUE THREAD

**Issue by markjbyrne81** [SBoudrias/mem-fs-editor#24]
The recent bump in version number dependencies has caused an issue in my generator where a I am using the slugify function from undersocre.string.

This was introduced in my generator once the version of lodash exceeded 2.4.1.  Was this behavior expected?

**Comment by SBoudrias** [comment]
Just to be clear this is about yeoman-generator, and `_` have never been an implicit arguments of copyTpl.

In in Yeoman, yes, `this._` is deprecated. You now need to provide your own Lodash version.

The easy fix is to add `this._ = _;` in your constructor. But the real solution is to use `this.fs.copyTpl` and be explicit about the arguments you provide your template.
