### ISSUE TITLE
copyTpl should support glob options

### ISSUE THREAD

**Issue by ZiggyQubert** [SBoudrias/mem-fs-editor#25]
the copyTpl function should support an optional options property in the same way that copy does.  More spicificly there should be some way to pass in globing options to paths that support globs.

**Comment by magmel48** [comment]
+1

**Comment by blai** [comment]
After seeing #44, I was about to jump on this again, but then I realize that it isn't necessary for this feature because you can simple do:

```js
// in yeoman generator
this.fs.copyTpl(glob.sync('src/**', {dot: true}), 'dist', context)
```

I can update the readme to include this example, what do you think?

**Comment by SBoudrias** [comment]
@blai ++ That'd be great!

**Comment by chrisathook** [comment]
Was this ever implemented?

**Comment by SBoudrias** [comment]
@chrisathook not yet. PR welcomed

**Comment by cm0s** [comment]
@blai ++
By the way, the whole template path must be specified : 
this.fs.copyTpl(glob.sync(generator.templatePath('src/**'), {dot: true}), 'dist', context)

**Comment by SBoudrias** [comment]
Forgot to close this issue, but passing glob options is now possible since 265f6aec266850408120a35da326c31e43d6f2d8
