### ISSUE TITLE
this.fs.delete shows "create" when deleting files

### ISSUE THREAD

**Issue by vganapat** [SBoudrias/mem-fs-editor#32]
Assume my folder structure is :

dir
    src
          test
                 HelloWorld.txt

For instance, if I do this.fs.delete("dir/src/test"); in my Yeoman generator: 

I get prompted about a conflict (why?). But anyways,

 conflict dir/src/test
? Overwrite dir/src/test? overwrite
    force dir/src/test
   create dir/src/test/HelloWorld.txt

I assume the force statements refers to deletion of the outer test folder. 

But, why, when deleting dir/src/test/HelloWorld.txt, does it say "create"? 

This "create" behavior as well as the "overwrite" prompt happens for this.fs.move as well. 

For reference, I am on: 

yo --version
1.4.7

**Comment by SBoudrias** [comment]
Yea, that's a bug with yeoman-generator. Please open an issue over at https://github.com/yeoman/generator/issues
