### ISSUE TITLE
this.fs.delete does not ... delete a file that was just added ...

### ISSUE THREAD

**Issue by binduwavell** [SBoudrias/mem-fs-editor#35]
In yeoman I copy a template folder structure and then based on some prompts I want to remove some of the files that the template copied. Yes I realize I could filter these files out during the copy or split the template copy into two parts. While either of these would be more efficient it makes the code more complicated.

I added the following step to my generator as a test:

``` javascript
testDeletion: function() {
  this.fs.write("foo", "foo");
  this.fs.delete("foo");
},
```

When the generator completes it creates foo. Now if I run the generator again, I get a diff message if I accept the change foo is deleted.

I expect that the first time through foo is not saved to the filesystem. And hence the second time through I should not see a diff prompt.

I'm not clear what issue #32 is about, I suspect these are different issues, but I could be wrong. Forgive me if I am :)

**Comment by SBoudrias** [comment]
Fixed! Thanks for reporting this issue!

**Comment by miguelsmuller** [comment]
any news ?

**Comment by SBoudrias** [comment]
@miguelsmuller if you have an issue either open an issue or ask a question on StackOverflow.

There's no point to spam a bunch of unrelevant tickets on my repos.

**Comment by miguelsmuller** [comment]
ok dude. sorry.

only I commented because it is the same with me. even though the updated packages.
from my point of view the topic still on the same subject.

but thank you anyway.
