### ISSUE TITLE
defaults option is ignored if falsy (e.g. empty string)

### ISSUE THREAD

**Issue by idpaterson** [SBoudrias/mem-fs-editor#36]
Commit 7adfb3a92a4c1201c3add77c2e2a766405930359 makes it impossible to default to a falsy value such as an empty string when the file being read does not exist. Prior to version 1.2.2 it was possible to set an empty string with `{ defaults: '' }`. This was a convenience as it allows a simple falsy evaluation of the file contents `if (contents) { ... }` without worrying about the exception.

The defaults option handling is in [actions/read.js line 10](https://github.com/SBoudrias/mem-fs-editor/blob/master/actions/read.js#L10)

I can submit a pull request with tests but I'm not sure which approach you would prefer to use to test whether `defaults` is provided. In a general case I would use something like `'defaults' in options` or `options.defaults !== undefined` but since the Buffer is intended to be created with a string it may be better to use `typeof options.defaults === 'string'` to both ensure that the option is defined and that it is a string.

**Comment by SBoudrias** [comment]
Check that `options.defaults` is a String.
