### ISSUE TITLE
move file in memory

### ISSUE THREAD

**Issue by floatdrop** [SBoudrias/mem-fs-editor#40]
From [`move`](https://github.com/SBoudrias/mem-fs-editor/blob/master/actions/move.js) code:

```js
this.copy(from, to, options);
this.delete(from, options);
```

If file was moved in memory it will be stored as `modified` and `deleted` file in `mem-fs`, even if it was never stored on fs. For example, if we copy `_package.json` and then move it to `package.json` yeoman will get two events from `mem-fs`:

```
   create package.json
   create _package.json
```

Should it instead remove `from` from `this.store` and just add `to`?

Cont. https://github.com/sindresorhus/generator-nm/pull/18

**Comment by SBoudrias** [comment]
This is a bug with yeoman-generator where it just always display created - even in the case of deletion. It's ticketed in the generator repo.

**Comment by floatdrop** [comment]
@SBoudrias yes, but this is about moving files explicitly. Should event about created file (which was right after renamed) be emitted from `commit`?

**Comment by SBoudrias** [comment]
Related issue to the double create issue: https://github.com/yeoman/generator/issues/820

Your last comment is not clear to me. But I believe the current behavior is correct. When you move a file, you effectively delete one from disk and create a new one. I don't think we should be handling this any other way - same for renaming.

The thing here is that mem-fs doesn't know it's not on disk. So it doesn't differentiate between files that haven't been committed and those who've been. What you want is for us to track the committed state of the files? And then we can skip unecessary events because they didn't touch the hard drive?

**Comment by floatdrop** [comment]
> What you want is for us to track the committed state of the files? And then we can skip unecessary events because they didn't touch the hard drive?

Basically, yes. From generator point of view - we create a file-system snapshot from empty state and commit it to real file-system. So if we create file in memory and then move it in memory - is it expected behaviour, that file on disk with old name (before moving) is deleted?

Thanks for clarification, I forgot about state on disk :dog:

**Comment by SBoudrias** [comment]
I'll think about this further. Might change the way we handle the files who're not on disk.

**Comment by sindresorhus** [comment]
It should normalize the transformations. So if you copy some files, then rename them, then delete one of them, it should only show what it actually will do on the filesystem, not what's done in-memory.

**Comment by iamstarkov** [comment]
faced the same issue yeoman/generator#833

**Comment by blai** [comment]
I see two ways to solve this:

1. In `mem-fs-editor`, filter out files with a `state === 'deleted'` but not existed on disk from [here](https://github.com/SBoudrias/mem-fs-editor/blob/master/actions/commit.js#L34). This solution prevents phantom deletion, but does not enhance yeoman to report on actual removal of files. 

2. In `generator`, check to see if a non-existing file has `state === 'deleted'` at [here](https://github.com/yeoman/generator/blob/d30b74c09ee088fe77096d69e250bc85fd497f3b/lib/util/conflicter.js#L107). The solution creates a tight dependency from yeoman generator to the proprietary `state` property of mem-fs-editor on vinyl objects. But it can now report on actual deletions of files, so it's an enhancement of Yeoman.

**Comment by SBoudrias** [comment]
@blai How about we go this way:

1. When we create a new file, one who doesn't exist on disk. We could add a state of "new".
2. Then if we delete a "new" file, we just remove it.

Then we just need to make sure the commit functionality is staying consistent.

**Comment by iamstarkov** [comment]
@SBoudrias’s suggestion sounds good

**Comment by SBoudrias** [comment]
Got to this tonight. It's now fixed!!
