### ISSUE TITLE
New method: extendJSON

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/mem-fs-editor#41]
I wonder if we could add a new method `#extendJSON()` to provide a JSON structure to overwrite the keys in an existing JSON file.

This seem like a pretty common pattern inside yeoman generators (like progressively building a package.json). And having syntax sugar on top of it might be useful.

**Comment by blai** [comment]
`readJSON` is currently taking an (optional) second parameter `defaults`, which is returned when the requesting JSON path does not exist. Do you think we can just change the behavior of using that as `defaults` to `extend`?

**Comment by eddiemonge** [comment]
It would save the trouble of doing `readJSON` (with optional specifying defaults) followed by `writeJSON`.
