### ISSUE TITLE
How to use copy() with options.process?

### ISSUE THREAD

**Issue by gormus** [SBoudrias/mem-fs-editor#42]
I am trying to copy a file and save an altered version to destination.

I couldn't find any information on _options.process_ usage. But when I try the snippet below, it doesn't work. Is this usage wrong?

```javascript
this.fs.copy(
  this.destinationPath('vendor/_bootstrap.scss'),
  this.destinationPath('sass/_bootstrap.scss'),
  {
    options: {
      process: function (contents) {
        var c = contents.replace('@import "bootstrap/variables";', '');

        return c;
      }
    }
  }
);
```

**Comment by SBoudrias** [comment]
Example: https://github.com/SBoudrias/mem-fs-editor/blob/master/actions/copy-tpl.js#L16-L20

Your issue is that you added an unnecessary `option` key.
