### ISSUE TITLE
Allow renaming on glob copy?

### ISSUE THREAD

**Issue by alexdresko** [SBoudrias/mem-fs-editor#43]
Appologies if this doesn't make sense or if the feature already exists.. I would like it if my template file names could have a replacable token in them... and when I copy, I want an opportunity to replace the token in the file name, or otherwise do whatever I want with the filename... 

Thoughts? Is that possible already?

**Comment by SBoudrias** [comment]
You can achieve the same result with JavaScript if/else, switch statement, etc.

Having template token in the path would just clutter the interface and make your code harder to follow.

```js
function (context) {
    var files = {
        'sass': 'tpl/style.sass',
        'css': 'tpl/style.css'
    };

    this.fs.copyTpl(
        files[context.type],
        'myoutput', // this can also be a dict of values if you need different output
        context
    );
}
```

**Comment by alexdresko** [comment]
I think this would be much easier to follow than what I'm having to do now... 
```
  ..copy("*.*", function(originalFileName) {
    return originalFileName.replace("SomeToken", someVariable);
  });
```

Right now, I'm having to copy each and process each individual file.. and my files are hard coded.. if I could process file names programmatically, that would be much better.

**Comment by SBoudrias** [comment]
@alexdresko You can use the commit filters for this https://github.com/SBoudrias/mem-fs-editor#commitfilters-callback

Processing file names automatically is definitively not something I plan on doing ATM.

**Comment by alexdresko** [comment]
I apologize for not being clearer. 

I'm working with a yeoman generator, and the yeoman.io documentation says, specifically, "It is worth noting that although this.fs exposes commit, you should not call it in your generator. Yeoman calls this internally after the conflicts stage of the run loop."

Can you not just expose a callback similar to options.process? It's a very similar concept. Instead of working with the content, I just want to work with the file name.

**Comment by SBoudrias** [comment]
Yeoman expose it's own interface for the commit filters. See "Transform output files through streams" at http://yeoman.io/authoring/file-system.html
