### ISSUE TITLE
.dot files copying

### ISSUE THREAD

**Issue by magmel48** [SBoudrias/mem-fs-editor#44]
Hello guys, thanks a lot for awesome work! 
I have the following code (from own yeoman generator):

```javascript
    glob('**', {
      cwd: this.sourceRoot(),
      dot: true
    }, function (err, files) {
      files.forEach(function (file) {
        this.fs.copyTpl(
          file,
          this.destinationRoot(this.appname),
          this
        );
      }.bind(this));

      cb();
    }.bind(this));
```

which throw AssertionError:
    AssertionError: Trying to copy from a source that does not exist: .babelrc

Could you explain, how I can copy .dot files with copyTpl method?

**Comment by SBoudrias** [comment]
I don't think it's related to having a `.` file. My guess is your glob search doesn't return full paths, so you try to copy a file from the wrong directory.
