### ISSUE TITLE
copyTpl should take process options like copy

### ISSUE THREAD

**Issue by jskrzypek** [SBoudrias/mem-fs-editor#48]
I can imagine some scenarios where we'd want to pass our own process function to `copyTpl()` to do some string replacement or other editing logic on a copied template file either before or after it's passed to `ejs.render()`.

In one of these scenarios, in yeoman, we generate a template file with `template()` where we populate an array based on various options selected by the user, say for angular module dependencies, and because we need to allow for multiple options being selected, as well as other injection later by other sub-generators we write the template like this:
```js
angular.module('<%= moduleName %>', [<% if (module1) { %>'module1',<% } %><% if (module2) { %>'module2',<% } %><% if (module3) { %>'module3',<% } %>
     // inject:modules start
     // inject:modules end
])
```
The annoying thing is that after only running this one generator, if we run our tests we automatically fail the linter because we necessarily have included a dangling comma in the above array. I guess we could write more templating logic to handle the commas alone, but given `ejs`'s syntax, that would quickly grow unwieldy. It would be great if we were able to resolve this with options passed to `template()`/`copyTpl()`.

I see two possible solutions to this problem if either pre- or post-`process` functions could be passed in the options: 
  * If we have a `postProcess` function, we could to inspect the array after templating and remove the dangling comma, perhaps using existing linters 
  * if we have a `preProcess` function we could write logic to determine what modules were selected by the user and and then add commas as necessary. e.g. we could write our template like this: 

  ```js
  angular.module('<%= moduleName %>', [ #=====modules hook=====#
        // inject:modules start
        // inject:modules end
  ])
  ```

  and then our `preProcess` function like this:

  ```js
  preProcess: function (content) {
      var moduleDeps = []
          .concat(module1 ? '\'module1\'' : [], module2 ? '\'module2\'' : [], module3 ? '\'module3\'' : []);
      return content.toString().replace(/#=====modules hook=====#/, moduleDeps.join(', ');
  }
  ```

Of course we could just use `copy()` and write the `process` logic for all of the replacements, but then we miss out on being able to use `ejs` for the simple value replacements.

Let me know what you think, I'm happy to work on a PR if people agree with me.

**Comment by SBoudrias** [comment]
Why not doing this in multiple steps inside your generator?

**Comment by jskrzypek** [comment]
What would be a good pattern for doing that? My understanding was that it's not possible to touch the same file twice in the same generator.

**Comment by SBoudrias** [comment]
> it's not possible to touch the same file twice in the same generator.

Of course it is possible :) There's no such limitation.

So I'd say:

- Step 1: read the file content
- Step 2: modify the file content manually
- Step 3: write the file

Or any other order you need; you may wish to first `copyTpl` and then read, etc.

Your use case is very specific and wouldn't make a great public API.
