### ISSUE TITLE
Upgrade EJS to 2.3.4

### ISSUE THREAD

**Issue by PhilippSoehnlein** [SBoudrias/mem-fs-editor#49]
Using mem-fs in a Yeoman generator (using ``fs.copyTpl``) may lead to horrible output, because of the restricted white space handling of EJS (see https://github.com/mde/ejs/pull/105). Since EJS 2.3.4 introduced ``<%_`` and ``_%>`` which should help with these kinds of problems, I'd like to ask you for an EJS upgrade.

**Comment by SBoudrias** [comment]
Semver range is valid with the new version. Just run `npm update`.
