### ISSUE TITLE
Can not write or copy files

### ISSUE THREAD

**Issue by daituzhang** [SBoudrias/mem-fs-editor#51]
Hi, I'm using node v4.1.1, not sure if it's causing the problem.
I was testing using the example in the introduction:

```javascript
var memFs = require('mem-fs');
var editor = require('mem-fs-editor');

var store = memFs.create();
var fs = editor.create(store);
console.log(fs.read('test.js'));
fs.write('test.js', 'var a = 1;');
```
output is 
`aaaaa` which was correct in the `test.js`
But the new string didn't get written into the file. (I've granted write permission on the file.)

I didn't get any error messages either, is there a way I can debug? Thank you

**Comment by SBoudrias** [comment]
mem-fs-editor only modify the state of the mem-fs store.

Once you're done modifying it, you need to write the file to disk yourself. https://github.com/SBoudrias/mem-fs-editor#commitfilters-callback
