### ISSUE TITLE
write to placeholder

### ISSUE THREAD

**Issue by Kratos-SA** [SBoudrias/mem-fs-editor#52]
Is it possible to write the new content to where a placeholder is and leave that placeholder there for future writes?

**Comment by SBoudrias** [comment]
I don't really understand your question. Can you add code example?

**Comment by Kratos-SA** [comment]
I have an angular project and I want to write the dependencies into the app.js file using yeoman. So when I create a new controller using yeoman it will automatically update my app.js file. So if I can write to a specific location in a file that would be great.

**Comment by SBoudrias** [comment]
@Kratos-SA checkout https://github.com/SBoudrias/AST-query/

**Comment by Kratos-SA** [comment]
I looked at that and it seems rather overkill and complicated for what I want to do. is there not a simpler solution. I have looked at gulp-inject but I would prefer to do it with yeoman.

**Comment by SBoudrias** [comment]
@Kratos-SA you can read then parse your files and replace a token with your new code if you want. But using an AST based solution is usually way more robust.
