### ISSUE TITLE
Add a method to create an empty directory

### ISSUE THREAD

**Issue by adamzr** [SBoudrias/mem-fs-editor#53]
There should be a method to create an empty directory. I'm not the only person who needs this, see http://stackoverflow.com/questions/29830927/creating-empty-directories-in-a-yeoman-generator

Thanks!

**Comment by SBoudrias** [comment]
I guess you saw the answer on SO. Just use `mkdirp`.

FWIW, git is another system who doesn't have any handling of empty directory. What you'd do (and what you'll see in boilerplates projects around the web) is add a `.gitkeep` empty file in directory who might be empty. That way you're sure empty directories are kept around and shared with your team.

As there's multiple work around and that there's potential interops issues with having empty directories. I don't intend to change mem-fs to handle directories ATM.
