### ISSUE TITLE
Expose a way to list files in memory

### ISSUE THREAD

**Issue by Swiip** [SBoudrias/mem-fs-editor#54]
That's just a suggestion coming from a recent need. I wanted to apply modifications on a collection of files already modified and in memory. But my context is too generic to allow me to now exactly the name of the files I want.

In some way, what I need at that point is an API like a `.list('src/**.*.js')`. `.exists` already exists but it doesn't allow to discover which files are in memory.

Finally, as a workaroud, I committed changes and used globby to list my files. It works but it's not really the best.

I looked quickly to the source code, it seems really simple to do as list files with glob patterns is already everywhere, it would only be exposing the feature. I can make a PR if the idea is ok.

**Comment by SBoudrias** [comment]
The mem-fs store itself expose utilities to iterate over the store or stream the files: https://github.com/SBoudrias/mem-fs/blob/master/index.js#L44 - could that be sufficient?

**Comment by Swiip** [comment]
I didn't think of looking directly in mem-fs thanks. I succeed, I just had to filter with minimatch manually.

```javascript
  this.fs.store.each(file => {
    if (minimatch(file.path, this.destinationPath(destinationFiles))) {
      console.log('file', file.path);
    }
  });
```

It works, is it enough and I close this?

**Comment by SBoudrias** [comment]
If that's working for your use case, then yeah I think we can close it :)
