### ISSUE TITLE
Make `fs` an option on `commit` such that a mock file system can be passed in

### ISSUE THREAD

**Issue by vjpr** [SBoudrias/mem-fs-editor#55]
The `mock-fs` library allows the creation of a mock file system. 

It has a mode to allow creating a mock `fs` object. See https://github.com/tschaub/mock-fs#mockfsconfig-options. This prevents problems with using it in the default way which interferes with `require` statements.

This small change to `mem-fs-editor` would allow the commit output to be tested in memory.

EDIT: Could also allow https://github.com/SBoudrias/mem-fs-editor/blob/master/test/commit.js tests to run faster.

**Comment by SBoudrias** [comment]
PR welcomed

**Comment by SBoudrias** [comment]
Looks to me like `mock-fs` version 4 doesn't require any extra options to work given it now mock the global node `fs` module.

Let me know if that's not the case and I'll reopen this issue.
