### ISSUE TITLE
Bug: Copy-tpl does not handle an array of files correctly

### ISSUE THREAD

**Issue by RyanZim** [SBoudrias/mem-fs-editor#59]
I am a collaborator at EJS. Someone just opened https://github.com/mde/ejs/issues/166 stating that they were receiving an error due to recent updates in EJS's error handling. We traced the issue back to the fact that mem-fs-editor sometimes calls `ejs.compile()` passing the `filename` option as an array. As I stated there:

> The official API docs explicitly specify that `filename` should be a _string_. http://ryanzim.github.io/ejs-api/global.html#Options

There should be some handling in `copy-tpl.js` to check if `filename` is an array.

This is a critical bug; this behavior affects `yeoman-generator`'s use of this module. :sos: 

If you want a quick patch in the meantime, you can fix the EJS dependency to v2.4.1.

**Comment by RyanZim** [comment]
@SBoudrias ping?

**Comment by SBoudrias** [comment]
Yeah, looks like a valid bug. Need to investigate how it end up receiving an array.

Especially given that mem-fs-editor copyTpl and copy method don't support files array as arguments.

**Comment by RyanZim** [comment]
@SBoudrias See https://github.com/Polymer/polymer-cli/issues/206#issuecomment-221736928:

> Until recently this `copyTpl()` could accept an array of file patterns to match against, even though this wasn't explicitly supported by it's dependency ejs. A recent change there now causes this to fail instead.

**Comment by RyanZim** [comment]
Also, what happens when you pass a glob to copyTpl?

**Comment by FredKSchott** [comment]
For anyone who runs into this same issue, here's our fix https://github.com/Polymer/polymer-cli/pull/207
