### ISSUE TITLE
Renaming a newly created directory throws "Trying to copy from a source that does not exist" error

### ISSUE THREAD

**Issue by nfriend** [SBoudrias/mem-fs-editor#61]
I'm trying to rename a directory as part of a Yeoman generator.  I have the following Yeoman directory structure:

```
root/
├── generators
│   └── app
│       ├── templates
│       │   └── app
│       │       └── widget
│       │           ├── widget.controller.ts
│       │           ├── widget.service.ts
│       │           └── widget.module.ts
│       └── index.js
└── .yo-rc.json
```

My Yeoman generator copies everything from the `templates` directory to the new app's destination directory.  As part of this process, I'd like to rename the `widget` folder to a name that the user enters earlier in the Yeoman process.  This is the relevant code from the Yeoman generator (`this.fs` is an instance of `mem-fs-editor`):

``` javascript
this.fs.copyTpl(this.templatePath('**/*'), this.destinationPath('.'), this.props);

this.fs.move(
    this.destinationPath('app/widget'),
    this.destinationPath('app/' + this.props.widgetName)
);
```

The call to `copyTpl` is correctly scaffolding and templating the app from the `templatePath` to the `destinationPath`.  However, when the `fs.move` operation is called, I get the following error message:

```
PS C:\Users\username\code\generator-dashboard-widget-test> yo dashboard-widget
? Your widget's name: (generator-dashboard-widget-test)
? Your widget's name: generator-dashboard-widget-test

events.js:154
      throw er; // Unhandled 'error' event
      ^
 AssertionError: Trying to copy from a source that does not exist: C:\Users\username\code\generator-dashboard-widget-test\app\widget
    at EditionInterface.exports._copySingle (C:\Users\username\code\generator-dashboard-widget\node_modules\mem-fs-editor\lib\actions\copy.js:45:3)
    at EditionInterface.exports.copy (C:\Users\username\code\generator-dashboard-widget\node_modules\mem-fs-editor\lib\actions\copy.js:23:17)
    at EditionInterface.module.exports [as move] (C:\Users\username\code\generator-dashboard-widget\node_modules\mem-fs-editor\lib\actions\move.js:4:8)
    at module.exports.generators.Base.extend.copyAppTemplate (C:\Users\username\code\generator-dashboard-widget\generators\app\index.js:54:17)
    at Object.<anonymous> (C:\Users\username\code\generator-dashboard-widget\node_modules\yeoman-generator\lib\base.js:431:23)
    at C:\Users\username\code\generator-dashboard-widget\node_modules\run-async\index.js:26:25
    at C:\Users\username\code\generator-dashboard-widget\node_modules\run-async\index.js:25:19
    at C:\Users\username\code\generator-dashboard-widget\node_modules\yeoman-generator\lib\base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

If I leave out the rename step, this process works without any issues, and I can verify that the `app/widget` folder does indeed exist.

Here's a bug I filed on the `yo` repository for the same issue: https://github.com/yeoman/yo/issues/455

**Comment by SBoudrias** [comment]
I think the issue is the virtual file system doesn't store references to folders. It might work using a glob pattern, but I'm not sure glob matching if going to work over the virtual files.

This is a bug.

**Comment by petrogad** [comment]
I had a similar issue, and used a setTimeout in order to attempt and execute the action after the files had been created. It's working ok, however it's most certainly a weak work around for the problem.

In my case I was attempting to:
 - Copy files from the destination location to a temp location
 - Overwrite files at the destination with template files
 - Copy back files from the temp location to the destination location.

by doing a setTimeout on the last step (with a 1500 ms), it seems like I'm able to get around the virtual file system (but again, hack)

**Comment by adovepf** [comment]
Yeah, this is definitely still affecting me. The workaround is not as simple as using a timer. Globbing doesn't work, so we're forced to move files one by one which is a real pain and we only have ~15 files needing to be moved. It'd be real unfortunate if you had more.

**Comment by KirankumarAmbati** [comment]
Is the issue still exists ? I'm facing similar thing. I used `setTimeout` as a hack but would like to know if it has any solution.

**Comment by SBoudrias** [comment]
@KirankumarAmbati as far as I know, that specific issue is fixed. Are you sure you're using the latest version?

If so, I'd suggest you to open a new issue so we can track your specific problem separately.
