### ISSUE TITLE
New Feature: Add support for mkdirp

### ISSUE THREAD

**Issue by gd46** [SBoudrias/mem-fs-editor#63]
Add support for mkdirp so empty directories can be generated as placeholders.

**Comment by SBoudrias** [comment]
Any reason you can't use [mkdirp](https://www.npmjs.com/package/mkdirp) directly? What would be the advantage of adding support for this in mem-fs?

**Comment by gd46** [comment]
Im working with creating a yo generator and was hoping that if mem-fs supported it, I could then add it in yo and use it the same as the other file functions without having to download another dependency.

**Comment by SBoudrias** [comment]
We had the same discussion before on https://github.com/SBoudrias/mem-fs-editor/issues/53

The gist of it is mem-fs is not a system tracking directories, it only tracks files.

**Comment by gd46** [comment]
I see, ok thanks
