### ISSUE TITLE
Copy not copying files to app root

### ISSUE THREAD

**Issue by codeNgamer** [SBoudrias/mem-fs-editor#73]
I have the following code and for the life of me I can't figure out what's wrong. I first get a prompt for conflict resolution with no filename on ['app.js', 'run.js', 'gulfpfile.js']. if i type 'y' to overwrite, I get error "Illegal operation on a directory". If I comment out objects for 'app.js', 'run.js' and 'gulfpfile.js', everything works fine. All these files are under templates/ btw
   
```javascript
const dest = this.destinationPath();
    const resources = [
      { uri: 'app.js', dest: '.' },
      { uri: 'run.js', dest: '.' },
      { uri: 'gulpfile.js', dest: '.' },
      { uri: 'app/**/*', dest: 'app' },
      { uri: 'public/**/*', dest: 'public' },
      { uri: 'spec/**/*', dest: 'spec' },
      { uri: 'views/**/*', dest: 'views' },
    ];
    _.forEach(resources, resource => {
      if (resource.dest) mkdirp.sync(resource.dest);
      this.fs.copy(
        this.templatePath(`${resource.uri}`),
        this.destinationPath(resource.dest)
      );
    });

```

**Comment by SBoudrias** [comment]
Then destination needs to be a file path - right now it points to a directory.

**Comment by codeNgamer** [comment]
Ahh thanks!
