### ISSUE TITLE
Allow to disable glob matching?

### ISSUE THREAD

**Issue by sinedied** [SBoudrias/mem-fs-editor#75]
I'm using [yeoman](yeoman.io) which uses your lib for file operations.

The problem I'm having is when I try to copy a file containing blob-matching characters, like `[merge].package.json`.

This file resolves as a blob and fails to copy properly. When I tried to escape the `[ ]` character with `\[merge\].package.json`, there is an issue in `copy.js` with this statement:

```js
  if (Array.isArray(from) || !this.exists(from) || glob.hasMagic(from)) {
```
`glob.hasMagic()` properly returns false, but `!this.exists()` matches because the test does not account for the escaped glob characters.

The simplest way to resolve this would be an option to `copy/copyTpl` to disable glob matching entirely, what do you think?

**Comment by SBoudrias** [comment]
Shouldn't `glob.hasMagic` return true in that case?

**Comment by sinedied** [comment]
No, because the "magic" characters have been escaped.

**Comment by SBoudrias** [comment]
So we should change `this.exists()` to account for escaped globs?

**Comment by sinedied** [comment]
@SBoudrias That would be a way to fix the issue, yes.

But seeing the code and the error returned here, I'm wondering it the `this.exists()` is pertinent here. If this check has to be made, it shouldn't it be after the globs are resolved?

**Comment by sinedied** [comment]
Would you accept a PR that adds a `noGlob: boolean` option to disable glob matching?

As the update to `fast-glob` have broken all my generators, since `()` characters make my path interpreted as glob, and no way to disable it 😞

**Comment by sinedied** [comment]
The workaround is not working anymore in the latest version :( (related #134 )

- previously using `globOptions: { noext: true }` worked as a workaround for special chars
- but now, even using `globOptions: { extglob: false }` and escaping special chars with`\\` do not work, because of the `globify` util that will force a glob when the file does not exists, and it can't find one because of the special chars.

Any ideas?

**Comment by SBoudrias** [comment]
Hey @sinedied, I'd recommend opening this issue on the underlying glob package https://github.com/mrmlnc/fast-glob - they might have a suggestion over there.

**Comment by sinedied** [comment]
@SBoudrias unfortunately, that won't help here. The options are working correctly, it's more by chance that the previous `noxext` option worked as a workaround.

The thing is that the solution already exists and is provided by `fast-glob`: `escaping special chars with `\\`. The problem is the `util.globify()` function called before the copy: https://github.com/SBoudrias/mem-fs-editor/blob/master/lib/util.js#L37-L55

It forces path normalization, which removes the `\\` to escape the special characters, and then break everything else. Would you be ok if I propose a PR with an option like `skipGlobCheck` to bypass the `util.globify` call?

**Comment by SBoudrias** [comment]
Yes, totally open for this. Let's add a `noGlob` to the option, and when it's passed, we can by-pass `globby` entirely.

**Comment by sinedied** [comment]
PR submitted: https://github.com/SBoudrias/mem-fs-editor/pull/185 🙂
