### ISSUE TITLE
Feature request: copyDir

### ISSUE THREAD

**Issue by alallier** [SBoudrias/mem-fs-editor#83]
It would be nice to have a copy directory feature which allows you to copy directories without files.

Use case this can allow us to copy skeleton directory structures without files having to exist these directories. Right now there is no way to copy an empty directory or even an empty directory with empty child directories.

**Comment by SBoudrias** [comment]
I'd suggest using mkdirp. Mem-fs-editor doesn't have support for directories themselves.

**Comment by alallier** [comment]
@SBoudrias no intentions to support directories?

**Comment by SBoudrias** [comment]
No, this would require very substantial changes. I'm not willing to put all that coding time myself at the moment.
