### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [SBoudrias/mem-fs-editor#98]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature,

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by SBoudrias** [comment]
Hey, too many packages depends on mem-fs-editor (and yeoman) for us to change the template syntax at the moment.

Thanks for the suggestion though :)

**Comment by Drulac** [comment]
It's possible to add an option for newers packages :-)
